name: 'Test Scanner POC'
description: 'Example of reusable action'
inputs:
  sonar-host:
    description: 'SonarQube host'
    required: true
  sonar-token:
    description: 'SonarQube token'
    required: true
runs:
  using: "composite"
  steps:
    - run: echo "Scanner version V1"
      shell: bash
    - name: Set permissions
      run: chmod +x ${{ github.action_path }}/run-scanner.sh
      shell: bash
    - name: Run scanner bash
      run: ${{ github.action_path }}/run-scanner.sh --workspace ${{ github.workspace }} --sonar-host ${{ inputs.sonar-host }} --sonar-token ${{ inputs.sonar-token }}
      shell: bash